<?php
namespace app\api\controller;


use think\Controller;

class Prints extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        defined('SELLER_ID') or define('SELLER_ID', intval(input('seller_id',0)));
    }

    //测试
    public function test()
    {
        if (!($machine_id = intval(input('machine_id', 0)))) finish(201, 'ID出错');
        $condition = [];
        $condition['seller_id'] = SELLER_ID;
        $condition['id']        = $machine_id;
        $condition['status']    = 0;
        if (!($machine = \think\Db::name('seller_print')->where($condition)->find()))
            finish(201, '数据有误');

        include_once (KERNEL_PATH.'/class/ShuWangPrint.class.php');
        $printStream = "\n--------------------------------\n";
        $printStream.= "\n  打单机测试                    \n";
        $printStream.= "\n--------------------------------\n";

//        if(!file_exists(APP_PATH.'Common/Conf/print.php')) finish(201, '接口未配置');
//
        $params['method']     = 'print.cloud.text';
        $params['appid']      = 172;
        $params['timestamp']  = time();
        $params['printid']    = date('YmdHis');
        $params['devid']      = '10954';
        $params['sign']       = \ShuWangPrint::getSign($params, 'La6Im0Hv3Bp6Zv7Ea6Yy0Er7Ue6Vx1Vg');
        $params['printstream']   =  $printStream;
        $result = \ShuWangPrint::httpRequest('http://api.shuwang.info/gateway/rest', json_encode($params));
        $result = json_decode($result, true);
        dump($result);exit();
        if($result['response']['status']==201) finish(200, '发送成功');
        finish(201, '发送失败:'.$result['response']['message']);
    }



}